### ISSUE TITLE
ENH -  Modify testing action so that it checks out its own repository

### ISSUE THREAD

**Issue by gabalafou** [Quansight-Labs/jupyter-a11y-testing#28]
If we want to be able to create a workflow in the JupyterLab repo that calls an action our repository for accessibility testing like so:

```yml
jobs:
  test-jupyterlab-accessibility:
    steps:
      uses: quansight-labs/jupyter-a11y-testing/.github/actions/accessibility-test-jupyterlab@main
      with:
        repo: ${{ github.repository }}
        ref: ${{ github.ref }}
```

then the testing action needs to know how to checkout the repo that it belongs to. I could hard-code it (as `quansight-labs/jupyter-a11y-testing`), but that makes it a bit more difficult to test the action via forking.

I thought the environment variable `$GITHUB_ACTION_REPOSITORY` would do the trick, but when I tested it out, it didn't work. First, I created a repo `gabalafou/action-sandbox` in which I put [a simple action that just prints the environment variables](https://github.com/gabalafou/action-sandbox/blob/8abb38a1488bfaa0773208429fb6827dfe7002b4/action.yml). Then, I created another repo with [a workflow that calls the action in the first repo](https://github.com/gabalafou/action-sandbox-2/blob/f6ac2ebeaba26545b31767cdf9a9b23e0ab04ce9/.github/workflows/env.yml). If you search the log of [one of the workflow runs](https://github.com/gabalafou/action-sandbox-2/actions/runs/3406855426/jobs/5665918452) you'll see the following line

```
GITHUB_ACTION_REPOSITORY=
```

which I think means that the environment variable contains an empty string and not `gabalafou/action-sandbox`, the repo that the contains the action.
